version: '3'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: nginx/Dockerfile
    ports:
      - "85:80"
    volumes:
      - ./frontend/src:/var/www/html

  php:
    build:
      context: ./frontend
      dockerfile: php/Dockerfile
    volumes:
      - ./frontend/src:/var/www/html
    depends_on:
      - frontend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
